In [8]:
import numpy as np
import scipy 
from scipy import linalg
import pprint as pp

In [9]:
M = [[1,2],[2,1],[3,4],[4,3]]
M = np.asarray(M)

svd = linalg.svd(M,full_matrices=False)

U = svd[0]
print("The value of U is:")
pp.pprint(U)

The value of U is:
array([[-0.27854301,  0.5       ],
       [-0.27854301, -0.5       ],
       [-0.64993368,  0.5       ],
       [-0.64993368, -0.5       ]])


In [10]:
sigma = svd[1]
print("The value of Sigma is:")
pp.pprint(sigma)

The value of Sigma is:
array([7.61577311, 1.41421356])


In [11]:
V_T = svd[2]
print("The value of V_transpose is:")
pp.pprint(V_T)

The value of V_transpose is:
array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])


In [12]:
matrix = np.matmul(M.T,M)
Evals,Evecs = scipy.linalg.eigh(matrix)

Evals = sorted(Evals, reverse=True)
print("The eigen values are:")
pp.pprint(Evals)

The eigen values are:
[58.0, 2.0]


In [13]:
Evecs = np.flip(Evecs,1)
print("The eigen vectors are:")
pp.pprint(Evecs)

The eigen vectors are:
array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])
